default:
  tags:
    - DRP19
    
build-app:
  stage: build
  script:
    - ./gradlew build
    
test-app:
  stage: test
  script:
    - ./gradlew test
    
deploy-app:
  stage: deploy
  script:
    - ./gradlew assemble