default:
  tags:
    - DRP19
    
before_script:
  - ./gradlew --stop
    
build-app:
  stage: build
  script:
    - ./gradlew build --no-daemon
  only:
    - master
    
test-app:
  stage: test
  script:
    - ./gradlew test
  only:
    - master
    
deploy-app:
  stage: deploy
  script:
    - ./gradlew assembleDebug
    - scp drp-book-app/app/build/outputs/apk/app-debug.apk ad4220@shell4.doc.ic.ac.uk:~/public_html/app.apk
  only:
    - master